### ISSUE TITLE
[BUG] Cyclic Import detected.

### ISSUE THREAD

**Issue by sujanchegu** [pesos/browser-history#19]
**Describe the bug**
While performing checks before opening a PR, I noticed `pylint` generated 
```

browser_history/__init__.py:2:0: C0411: first party import "from browser_history.utils import get_history" should be placed before "from . import browsers" (wrong-import-order)
************* Module browser_history.generic
browser_history/generic.py:1:0: R0401: Cyclic import (browser_history.generic -> browser_history.utils) (cyclic-import)
```

**To Reproduce**
1. Go to 'Root directory of the local repo' & activate your env.
2. Run 'pylint browser_history'
3. Don't have to Scroll :)

**Expected behavior**
Those warnings shouldn't be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/43275517/93628805-ce872d00-fa04-11ea-9846-ffed7aa7ed4d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g.Firefox]
 - `browser-history` [master]
 - Python version: [e.g. 3.8.2]

**Comment by Samyak2** [comment]
One fix could be moving `get_history` to a different file (other than `__init__.py` or `generic.py`)

**Comment by sujanchegu** [comment]
Can you explain the thought process of why it shouldn't be moved to `__init__.py` and `generic.py` ?

**Comment by Samyak2** [comment]
My reasoning behind not adding it in `__init__` was this: the `get_history` function requires `generic.Browser`, so if you import that in `__init__` it will lead to `generic` getting imported everytime the module is loaded.

I took a second look at it now and it seems that `generic` is loaded anyway (through `browsers`) and so you could have `get_history` in `__init__` as long as the namespace is not polluted.

`get_history` shouldn't be in `generic` because I think it doesn't belong there. `generic` is for abstract implementations while `get_history` is a utility function.

**Comment by sujanchegu** [comment]
Right. I'll work on this.
