### ISSUE TITLE
[BUG] CI Failing

### ISSUE THREAD

**Issue by Samyak2** [pesos/browser-history#95]
**Describe the bug**

The CI is currently failing on master. The issues seems to be from codecov.

Logs from GitHub Actions:
```
Run codecov/codecov-action@v1
/bin/bash codecov.sh -f ./coverage.xml -n  -F unittests -Z
codecov.sh: line 2: syntax error near unexpected token `<'
codecov.sh: line 2: `<html><head>'
Error: Codecov failed with the following error: The process '/bin/bash' failed with exit code 2
```

Codecov has not been updated recently, so we can rule out any changes in codecov (for python).

**Expected behavior**

CI should pass if all tests pass (which they are).

**Additional context**

The failures occurred after #92 and #93 were merged.

**Comment by lucasace** [comment]
@Samyak2 
https://github.com/codecov/codecov-bash/issues/146
I dont think this is a issue caused by any PR.
As per [this](https://github.com/codecov/codecov-bash/issues/146#issuecomment-720059101), this issue started affecting repos  since yesterday.
Im not quite sure if they have fixed it yet though

**Comment by Samyak2** [comment]
@lucasace thank you for looking into it.

As the issue has been fixed, I'll try re-running the jobs.

**Comment by Samyak2** [comment]
It works.
Thank you.
